### ISSUE TITLE
Auto Divination plugin not working

### ISSUE THREAD

**Issue by krakenguy** [RSKraken/Kraken#13]
The divination plugin stays at an Unknown state permanently causing it to not do anything.
Tested manually walking to the locations and starting harvesting by myself with no luck. ( Flickering and Bright )

Versions 1.5.34-pre and 1.5.41-pre both affected.
![image](https://user-images.githubusercontent.com/83665915/117046180-0be0c680-ad19-11eb-8769-289e6e4ce23f.png)

**Comment by RSKraken** [comment]
I believe this is fixed now, thank you for reporting.
