### ISSUE TITLE
Won't auto-login if account has two factor authentication

### ISSUE THREAD

**Issue by theguyegor** [RSKraken/Kraken#14]
Would be great if the bot would still login if account has two factor authentication. Currently it just sits on login screen.

**Comment by RSKraken** [comment]
Can you explain the process of logging in with authenticator? The login process of the client is complex as we invoke internal game functions, and adding this may be difficult.

**Comment by Dewera** [comment]
I'll provide some info here as I've had this issue a year or so ago. So RS uses Google authenticator to generate their codes, and to my knowledge there's no (easy) way to pipe data from there to a client (which means manual entry is required.) The easiest way to solve this imo is to just have a check at the login stage to see if user has been prompted for a 2FA code (looking at packets returned after submitting login data is probably going to be easiest here or maybe just hook the function that presents the entry box) and prompt them to manually enter the code into a console window or something (if needed) and proceed from there.

Another way to solve could just be to allow user to manually login (toggle auto login in client) and force users to do so if they need to refresh the 30 day 'trust' period for 2FA.

**Comment by RSKraken** [comment]
We finally support this now!
