### ISSUE TITLE
ED3 Teleport out with food left

### ISSUE THREAD

**Issue by Semajian** [RSKraken/Kraken#15]
Running the bot with a strong enough account to tank all the way to the barrier to the zombies without eating all food - once it clears the mobs before the barrier it just idles rather than teleporting out.

**Comment by Cecire** [comment]
I am having the same issue.

**Comment by RSKraken** [comment]
Can you share an image of this happening?

**Comment by Gensk121** [comment]
https://ibb.co/dc7XGyT here's an image of where it sits.

**Comment by RSKraken** [comment]
We're removing most official plugins soon as we support creating Java plugins now.
