### ISSUE TITLE
Child widgets not returning correct data from API

### ISSUE THREAD

**Issue by JackCurtis98** [RSKraken/Kraken#21]
Child widgets aren't returning the correct information from the API. Example below in pics:

![image](https://user-images.githubusercontent.com/22086574/120123725-e2219f00-c1f3-11eb-93b9-f9fb0244086a.png)
![image](https://user-images.githubusercontent.com/22086574/120123731-e948ad00-c1f3-11eb-84b7-fc3d3efb9495.png)

<3.

**Comment by RSKraken** [comment]
This has been fixed. Thank you for reporting.
