### ISSUE TITLE
Included mining script -> Bronze orebox not detected

### ISSUE THREAD

**Issue by TienTieten** [RSKraken/Kraken#23]
When mining tin ore, the bronze orebox doesnt get detected. Also a option to mine bronze ore isnt displayed.

**Comment by demeterxx99** [comment]
Bronze ore box is not supported currently. 

There is no option to mine 'bronze ore' because it doesn't exist. Kraken could add support for _copper_ ore.

**Comment by TienTieten** [comment]
> 
> 
> Bronze ore box is not supported currently.
> 
> There is no option to mine 'bronze ore' because it doesn't exist. Kraken could add support for _copper_ ore.

It does support mining TIN ore, wich goes into a bronze orebox....

**Comment by RSKraken** [comment]
We're removing most official plugins soon as we support creating Java plugins now.
