### ISSUE TITLE
Suggestion: Add a method for getting an array of click options for NPCs/SceneObjects.

### ISSUE THREAD

**Issue by DevinDuBose** [RSKraken/Kraken#24]
It would be extremely useful for scripting if we could validate the click options on NPCs and Objects. When getting nearby SceneObjects by name, they don't always contain the same click options. IE: When doing divination, there are places with additional energy rifts that do not contain a "convert memories" option.

**Comment by RSKraken** [comment]
Hmm.. I'm not really sure this request is fit for our software at this time. It would require quite the amount of additional code to account for dynamic variables related to the options. I believe this can be handled in other ways (i.e. checking ids, convars.)
