### ISSUE TITLE
Bug: Widget child array index out of bounds exception  within native method

### ISSUE THREAD

**Issue by titandino** [RSKraken/Kraken#26]
When getting the widget child array on some widgets will give an array index out of bounds exception saying the correct child size is out of bounds for array of length 0. My guess is that the child array is not being initialized to the correct size as the exception is trying to access the correct size.

Reproduce by calling printWidgetText in the example plugin on 1430 group.

**Comment by RSKraken** [comment]
You're correct, there's 2 widget children list and I forgot to add the 2nd one, we fixed this a bit ago. Thanks for reporting.
