### ISSUE TITLE
Crashing when entering game from lobby (kraken-1.4.24-pre)

### ISSUE THREAD

**Issue by demeterxx99** [RSKraken/Kraken#3]
kraken-1.4.24-pre

Crashes when entering game from lobby. Doesn't happen first time initially logging in. Only happens after it's been afk kicked from game or manually returned to lobby.

[rs2client.exe.9852.zip](https://github.com/RSKraken/Kraken/files/6414148/rs2client.exe.9852.zip)

**Comment by RSKraken** [comment]
Test this on the newest patch, and open an issue if it's still there.
