### ISSUE TITLE
Account settings dialog too small

### ISSUE THREAD

**Issue by BotMit** [RSKraken/Kraken#30]
Since updating Kraken I’ve had to re enter all accounts, as has everyone, in doing so I have noticed the accounts settings dialog has changed to a set size which now makes it difficult to read the settings and there’s no option to maximise the dialog.

**Comment by RSKraken** [comment]
The window is the optimal size now. You can change the column size by moving the slider in the center.

https://github.com/RSKraken/Kraken/releases/tag/kraken-3.37.171-pre
