### ISSUE TITLE
Insert not working/crash error

### ISSUE THREAD

**Issue by USJonny** [RSKraken/Kraken#32]
Everything worked fine about a week ago, came back to use it again and the insert key isn't opening the menu and when I close the game out I get a crash report.

Below are the paths that I use and the other picture is the crash report.

![image](https://user-images.githubusercontent.com/57279757/124199628-f7ab1280-da98-11eb-90f5-628b313c2f8d.png)

![image](https://user-images.githubusercontent.com/57279757/124199616-f0840480-da98-11eb-838b-e982c9308c16.png)

AV is disabled
Compatibility mode is off
No public/custom plugins or scripts being used

**Comment by RSKraken** [comment]
This isn't your personal support, and I'm not instructing you how to provide proper crash dumps, etc.
