### ISSUE TITLE
Bug With The Breaking System!

### ISSUE THREAD

**Issue by JoshDraco** [RSKraken/Kraken#7]
![ss](https://user-images.githubusercontent.com/83301232/116955550-cbd30280-ac8a-11eb-922b-38ce8c6c868e.PNG)

So as shown in the photo I have the break system set up to take a break every 30 minutes for 10 minutes I was watching the bot when it was coming up to take a break I saw the red writing on the top left saying something to do with the bot breaking  as I watched it for a couple more minutes just incase it did not take the break and the bot never took its break and continued to mine.

**Comment by RSKraken** [comment]
Try setting up a really long break 1 minute into gameplay, and see if it ever triggers. There are some other settings that modify how breaks are taken, and I'm not sure if this is a bug.

**Comment by JoshDraco** [comment]
What other settings mess with the breaks ?

**Comment by RSKraken** [comment]
The bot has an internal efficiency value to determine how well it plays, and the lower it is, the higher chance of breaking.

**Comment by RSKraken** [comment]
Closing unless more testing has been done.
